name: lm_labs_flutter_lints
description: LM Labs recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
repository: https://github.com/glemartret/lm_labs_flutter_lints
issue_tracker: https://github.com/glemartret/lm_labs_flutter_lints/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
version: 0.1.0

environment:
  flutter: ">=3.22.0"
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter_lints: ^4.0.0
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.
